In [1]:
import torch
import torch.nn as nn

class UNet(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.init_conv = nn.Conv2d(1, 256, 1, padding=0)
        
    def forward(self, x):
        out = self.init_conv(x)
        return out

/opt/conda/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
unet = UNet()

test = torch.randn(1, 256, 256)
result = unet(test)

print(result.shape)

torch.Size([256, 256, 256])


In [3]:
dim_mults = (1, 2, 4)
dims = [256, *map(lambda m: 256 * m, dim_mults)]

In [4]:
in_out = list(zip(dims[:-1], dims[1:]))
print(in_out)

[(256, 256), (256, 512), (512, 1024)]


In [5]:
TIMESTEP = 1000
batch_size = 4
t = torch.randint(0, TIMESTEP, (batch_size,)).long()    
print(t)

tensor([983, 394, 220, 378])


In [6]:
m = nn.Identity(54, unused_argument1=0.1, unused_argument2=False)
input = torch.randn(128, 20)
output = m(input)

print(output.size())
print(input)
print(output)


torch.Size([128, 20])
tensor([[ 0.9044, -0.8494, -0.4632,  ...,  1.4992,  0.0891,  1.0323],
        [ 0.9041, -0.4717,  1.0163,  ...,  0.7412, -1.3716, -0.3130],
        [ 2.4795, -0.3741,  0.3613,  ...,  0.3731,  0.3312,  0.2139],
        ...,
        [-0.7974, -0.0933,  0.3821,  ..., -0.1604, -0.4416, -1.1277],
        [ 0.4832, -0.4118, -0.7638,  ..., -1.4519,  0.4888, -1.4854],
        [ 2.8029, -0.9059,  2.3978,  ...,  1.5017, -0.2909,  0.0089]])
tensor([[ 0.9044, -0.8494, -0.4632,  ...,  1.4992,  0.0891,  1.0323],
        [ 0.9041, -0.4717,  1.0163,  ...,  0.7412, -1.3716, -0.3130],
        [ 2.4795, -0.3741,  0.3613,  ...,  0.3731,  0.3312,  0.2139],
        ...,
        [-0.7974, -0.0933,  0.3821,  ..., -0.1604, -0.4416, -1.1277],
        [ 0.4832, -0.4118, -0.7638,  ..., -1.4519,  0.4888, -1.4854],
        [ 2.8029, -0.9059,  2.3978,  ...,  1.5017, -0.2909,  0.0089]])


In [42]:
import math

dim = 256
half_dim = dim // 2
embeddings = math.log(10000) / (half_dim - 1) 
embeddings = torch.exp(torch.arange(half_dim) * -embeddings)
embeddings = time[:, None]
print(embeddings)

tensor([1.0000e+00, 9.3004e-01, 8.6498e-01, 8.0447e-01, 7.4820e-01, 6.9586e-01,
        6.4718e-01, 6.0190e-01, 5.5980e-01, 5.2064e-01, 4.8422e-01, 4.5034e-01,
        4.1884e-01, 3.8954e-01, 3.6229e-01, 3.3695e-01, 3.1337e-01, 2.9145e-01,
        2.7106e-01, 2.5210e-01, 2.3447e-01, 2.1806e-01, 2.0281e-01, 1.8862e-01,
        1.7543e-01, 1.6315e-01, 1.5174e-01, 1.4113e-01, 1.3125e-01, 1.2207e-01,
        1.1353e-01, 1.0559e-01, 9.8203e-02, 9.1333e-02, 8.4944e-02, 7.9002e-02,
        7.3475e-02, 6.8335e-02, 6.3555e-02, 5.9109e-02, 5.4974e-02, 5.1128e-02,
        4.7552e-02, 4.4225e-02, 4.1131e-02, 3.8254e-02, 3.5578e-02, 3.3089e-02,
        3.0774e-02, 2.8622e-02, 2.6619e-02, 2.4757e-02, 2.3025e-02, 2.1415e-02,
        1.9916e-02, 1.8523e-02, 1.7227e-02, 1.6022e-02, 1.4901e-02, 1.3859e-02,
        1.2890e-02, 1.1988e-02, 1.1149e-02, 1.0369e-02, 9.6439e-03, 8.9692e-03,
        8.3418e-03, 7.7583e-03, 7.2155e-03, 6.7108e-03, 6.2413e-03, 5.8047e-03,
        5.3986e-03, 5.0210e-03, 4.6697e-

In [44]:
9.3004e-01

0.93004

In [46]:
8.6498e-01

0.86498

In [47]:
1.0000e-04

0.0001