In [3]:
import torch
import torch.nn as nn

class UNet(nn.Module):
    def __init__(self):
        super().__init__()
        
        self.init_conv = nn.Conv2d(1, 256, 1, padding=0)
        
    def forward(self, x):
        out = self.init_conv(x)
        return out

/opt/conda/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [4]:
unet = UNet()

test = torch.randn(1, 256, 256)
result = unet(test)

print(result.shape)

torch.Size([256, 256, 256])


In [5]:
dim_mults = (1, 2, 4)
dims = [256, *map(lambda m: 256 * m, dim_mults)]

In [6]:
in_out = list(zip(dims[:-1], dims[1:]))
print(in_out)

[(256, 256), (256, 512), (512, 1024)]


In [12]:
TIMESTEP = 1000
batch_size = 4
t = torch.randint(0, TIMESTEP, (batch_size,)).long()    
print(t)

tensor([239, 830, 784, 452])


In [13]:
m = nn.Identity(54, unused_argument1=0.1, unused_argument2=False)
input = torch.randn(128, 20)
output = m(input)

print(output.size())
print(input)
print(output)


torch.Size([128, 20])
tensor([[-0.1440, -1.3995,  0.3327,  ...,  0.1571, -0.8933, -2.4459],
        [-0.7471,  0.1377,  1.1579,  ..., -1.2415, -0.3073, -0.8189],
        [-0.7600, -0.1637, -1.9274,  ...,  0.9221, -1.6212,  0.3363],
        ...,
        [ 0.1674, -0.6929,  1.5903,  ...,  0.1568, -0.0826,  1.0039],
        [-0.9607,  0.7214, -1.1941,  ..., -0.6733, -0.3382,  1.5147],
        [ 1.8804, -1.8156, -1.1162,  ...,  0.8634,  0.4051, -0.7382]])
tensor([[-0.1440, -1.3995,  0.3327,  ...,  0.1571, -0.8933, -2.4459],
        [-0.7471,  0.1377,  1.1579,  ..., -1.2415, -0.3073, -0.8189],
        [-0.7600, -0.1637, -1.9274,  ...,  0.9221, -1.6212,  0.3363],
        ...,
        [ 0.1674, -0.6929,  1.5903,  ...,  0.1568, -0.0826,  1.0039],
        [-0.9607,  0.7214, -1.1941,  ..., -0.6733, -0.3382,  1.5147],
        [ 1.8804, -1.8156, -1.1162,  ...,  0.8634,  0.4051, -0.7382]])
